# Generated by Django 3.0.2 on 2020-02-09 12:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0003_auto_20200209_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='engine',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
