# Generated by Django 3.0.2 on 2020-02-09 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0004_bike_engine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bike',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='bike',
            name='img3',
        ),
    ]
