# Generated by Django 3.0.2 on 2020-02-11 05:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0006_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='img2',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bike',
            name='img3',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
