# Generated by Django 3.0.2 on 2020-02-11 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0007_auto_20200211_1107'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Booking',
            new_name='Book',
        ),
    ]
