# Generated by Django 3.0.2 on 2020-02-11 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0008_auto_20200211_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bike',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='bike',
            name='img3',
        ),
    ]
