# Generated by Django 3.0.2 on 2020-02-11 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0010_auto_20200211_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bike',
            name='user_id',
        ),
    ]
