# Generated by Django 3.0.2 on 2020-02-11 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='mobileno',
            field=models.CharField(max_length=50),
        ),
    ]
