# Generated by Django 3.0.2 on 2020-02-15 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200211_1135'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
